### ISSUE TITLE
How can I use RS helios 32 ?

### ISSUE THREAD

**Issue by arjunskumar** [HViktorTsoi/rs_to_velodyne#7]

**Comment by oskarmue** [comment]
Hey did you figure it out?
I use a Bpearl, which has 32 rings as well.
Or did you find a different way to transform the pcl?

**Comment by arjunskumar** [comment]
I modify the code my own

**Comment by Gatsby23** [comment]
> I modify the code my own

Hi, sorry for troubing you. I have met the same problem as you recently. Could you please give me some tips about how to modify the code ? Thank you very much
