### ISSUE TITLE
where to find RING_ID_MAP for other series?

### ISSUE THREAD

**Issue by srinivasrama** [HViktorTsoi/rs_to_velodyne#8]
How do you map the ring information of ruby sensor?

**Comment by HViktorTsoi** [comment]
Hi, there is no need to find ring map, just configure the rs_driver to output `XYZIRT` format point cloud, then use
rosrun rs_to_velodyne rs_to_velodyne XYZIRT XYZIRT
to convert the point cloud;

If necessary, the RING_ID_MAP can be found in the official documentation of robosense LiDAR https://www.robosense.ai/en/resources.
